export const environment = {
  application_title : "VolleyBall",
  start_message: "Welcome to my personal hobby project: VolleyBall",
  ip_title : "http://localhost:4200",
  db_title : "MongoDB",
  success_message: " added successfully",
  success_message_update: " updated successfully",
  player_success_message: "Player added successfully",
  player_success_message_update: "Player updated successfully",
  registration_success_message: "Registration successful",
  username_required: "Username is required",
  password_required: "Password is required",
  team_country_required: "Country is required",
  team_year_required: "Year is required",
  player_name_required: "Name is required",
  registration_failed_message: "Registration failed",
  registration_info_message: "Please fill the following form to register a new user ",
  initial_mesage:"",
  enter_password: "Re-enter Password here",
  password_does_not_match: "Password do not match",
  geosearch_field_required:"Latitude,Longitude and distance are required fields",
  search_field_required:"Search field is required ",
  country_required_fields:"Country and year are required fields",
  registration_required_fields:"Username and password are required fields",
  login_to_view: "Kindly login to view a team",
  page_not_found: "404 error Page not found",
  guest: "Guest",
  production: false
};
